### ISSUE TITLE
请问这里可以骂人吗

### ISSUE THREAD

**Issue by kzoacn** [laozhen/xdxminer#1]
我们这些打游戏的本来就没显卡了，全靠主机过活。你今天做了xbox，明天做什么，我想都不敢想！

**Comment by sdogsq** [comment]
The hashrate on XBox Serires X (1.10 MH/s) is way too low to be monetized yet. I suppose the author just develop this for fun. However, the author provides a feasible way that may be developed and utilized in the future. I agree it is potentially harmful to gamers.

**Comment by lm902** [comment]
您好，根据[GitHub社区指南](https://docs.github.com/en/github/site-policy/github-community-guidelines#what-is-not-allowed)，不能。

**Comment by dogbutcat** [comment]
目测是国人搞的 那就贴个链接吧 各施主耗子尾汁

[央行：虚拟货币相关业务活动属于非法金融活动，坚决依法取缔](https://www.ithome.com/0/577/362.htm)

**Comment by wangyangwazi** [comment]
这位可真是一点都不当人，觉得自己很机灵？

**Comment by laozhen** [comment]
Closing this issue. Please focus on the technology of this project.
